[DDO-3139] Refactor selector to support addition of `--changed-files-list` to `thelma render` (#154)

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -17,6 +17,57 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+
+      - name: check-errorf
+        run: |
+          #!/bin/bash
+          
+          set -eo pipefail
+          
+          echo 'Scanning for usage of `fmt.Errorf`...'
+          echo
+          
+          if grep -nr --include \*.go fmt.Errorf internal; then
+            cat <<EOF
+          
+          -----------------------------------------------------------------
+          ERROR: Usage of \`fmt.Errorf\` detected!
+          
+          Please use \`errors.Errorf\` instead.
+          
+          This allows us to log errors with stack traces:
+            https://github.com/rs/zerolog#error-logging-with-stacktrace
+          -----------------------------------------------------------------
+          
+          EOF
+            exit 1
+          fi
+
+      - name: check-errors-package
+        run: |
+          #!/bin/bash
+          
+          set -eo pipefail
+          
+          echo 'Scanning for usage of "errors" package...'
+          echo
+
+          if grep -nr --include \*.go '^\(import\)?[[:space:]]*"errors"' internal; then
+            cat <<EOF
+          
+          -----------------------------------------------------------------
+          ERROR: Usage of "errors" package detected!
+          
+          Please use "github.com/pkg/errors" instead.
+          
+          This allows us to log errors with stack traces:
+            https://github.com/rs/zerolog#error-logging-with-stacktrace          
+          -----------------------------------------------------------------
+          
+          EOF
+            exit 1
+          fi
+
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v2
         with:
